spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/pw-security-realm

# Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, circuitbreakers
  metrics:
    tags:
      application: ${spring.application.name}

# Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        failureRateThreshold: 20
        minimum-number-of-calls: 4
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

keycloack:
  auth:
    jwt-set-uri: http://localhost:8091/realms/pw-security-realm/protocol/openid-connect/certs

server:
  port: 9000

security:
  excluded:
    urls: /actuator/**, /swagger-ui.html, /swagger-ui/**, /docs/**, /v3/api-docs/**, /swagger-resources/**, /api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: User Service
      url: /docs/user-service/v3/api-docs
    urls[1]:
      name: Device Service
      url: /docs/device-service/v3/api-docs
  api-docs:
    path: /v3/api-docs