spring:
  application:
    name: ingestion-service

  kafka:
    bootstrap-servers: localhost:9094
    template:
      default-topic: energy-usage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082